databases:
  - name: pubmining
    databaseName: pubmining
    user: pubmining

services:
  - type: web
    name: pubmining
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -b 0.0.0.0 backend.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pubmining
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: off
      - key: CORS_ALLOWED_ORIGINS
        value: https://qrconnects.netlify.app